language: node_js
node_js:
  - '0.12'
before_script:
  - sleep 15
  - npm install -g bower grunt-cli
  - bower install
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
